astyle --recursive -A2 -t2 -U -m0 -j -k3 -W3 --mode=c -c -M72 -n "*.cpp"
astyle --recursive -A2 -t2 -U -m0 -j -k3 -W3 --mode=c -c -M72 -n "*.hpp"
astyle --recursive -A2 -t2 -U -m0 -j -k3 -W3 --mode=c -c -M72 -n "*.h"
astyle --recursive -A2 -t2 -U -m0 -j -k3 -W3 --mode=c -c -M72 -n "*.c"
astyle --recursive -A2 -t2 -U -m0 -j -k3 -W3 --mode=c -c -M72 -n "*.hh"
astyle --recursive -A2 -t2 -U -m0 -j -k3 -W3 --mode=c -c -M72 -n "*.cc"
astyle --recursive -A2 -t2 -U -m0 -j -k3 -W3 --mode=c -c -M72 -n "*.test"
